name: Rust

on:
  push:
    branches: [ main, codecov-setup ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: llvm-tools-preview
        
    - name: Set up path
      run: export PATH="$PATH;/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin"
         | echo $PATH

    - name: Run tests
      run: RUSTFLAGS="-C instrument-coverage" LLVM_PROFILE_FILE="json5format-%m.profraw" cargo test --lib
      
    - name: Measure coverage
      run: llvm-profdata merge -sparse json5format-*.profraw -o json5format.profdata
         | llvm-cov report --use-color --ignore-filename-regex='/.cargo/registry' --instr-profile=json5format.profdata --object target/debug/deps/lib-*

    - uses: codecov/codecov-action@v1
      with:
        directory: coverage
